### PR TITLE
Blocklist broken GDEF and morx tables

### LINKED ISSUE #328: Support GDEF blocklisting
harfbuzz has a per font GDEF table blocklist, to skip some "malformed" fonts. We don't support it yet. Will be possible only after a complete transition to Rust.

### PR DESCRIPTION
**Pull request by behdad**
Fixes https://github.com/harfbuzz/harfrust/issues/328

### CODE REVIEW

File: harfrust/src/hb/aat/mod.rs [hunk 1]
```diff
@@ -80,12 +80,36 @@ pub struct AatTables<'a> {
     pub feat: Option<Feat<'a>>,
 }
 
+/// Encodes three 21-bit values into a single u64 for table fingerprinting.
+const fn encode3(x: u32, y: u32, z: u32) -> u64 {
```
Comment (dfrg) [inline harfrust/src/hb/aat/mod.rs]: Looks like we already have this as HB_CODEPOINT_ENCODE3 in algs.rs?

File: harfrust/src/hb/ot/mod.rs [hunk 2]
```diff
@@ -725,3 +729,70 @@ impl ClassDefInfo {
         }
     }
 }
+
+/// Encodes three 21-bit values into a single u64 for table fingerprinting.
+/// Matches HB_CODEPOINT_ENCODE3 from harfbuzz.
+const fn encode3(x: u32, y: u32, z: u32) -> u64 {
```
Comment (dfrg) [inline harfrust/src/hb/ot/mod.rs]: Same as above.

**Review by dfrg — APPROVED** [review]
LGTM with a couple nits about reusing existing code.

File: harfrust/src/hb/ot/mod.rs [hunk 3]
```diff
@@ -725,3 +729,70 @@ impl ClassDefInfo {
...
+    ((x as u64) << 42) | ((y as u64) << 21) | (z as u64)
+}
+
+/// Blocklist specific broken GDEF tables identified by the combination of
+/// GDEF, GSUB, and GPOS table lengths.
+///
+/// See https://lists.freedesktop.org/archives/harfbuzz/2016-February/005489.html
+fn is_gdef_blocklisted(table_ranges: &TableRanges) -> bool {
```
Comment (khaledhosny) [inline harfrust/src/hb/ot/mod.rs:752]: The HarfBuzz code has more comments, do we want to copy them over here, or at least link to the HarfBuzz file?
